spring:
  application:
    name: application
  jmx:
    default-domain: scve

  datasource:
    url: jdbc:postgresql://localhost:5432/SCVE
    username: postgres
    password: 'root'
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
